import os
import json
import uuid
import re
import math
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ─── Audit Log Helpers ────────────────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ─── Signal 1: LLM via Groq ───────────────────────────────────────────────────

def llm_signal(text):
    """
    Asks Groq whether the text reads as AI-generated or human-written.
    Returns a float between 0.0 (definitely human) and 1.0 (definitely AI).
    """
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and assess the probability that it was generated by an AI writing tool.

Consider:
- Semantic coherence and predictability
- Phrasing patterns common in AI output (hedging language, overuse of transitions, overly balanced structure)
- Vocabulary choices and uniformity
- Whether the writing feels genuinely personal or templated

Respond with ONLY a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Text to analyze:
{text}"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"LLM signal error: {e}")
        return 0.5


# ─── Signal 2: Stylometric Heuristics ────────────────────────────────────────

def stylometric_signal(text):
    """
    Measures three statistical properties that differ between AI and human writing.
    Returns a float between 0.0 (human-like) and 1.0 (AI-like).
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())
    total_words = len(words)

    if total_words < 10 or len(sentences) < 2:
        return 0.5  # not enough data to score reliably

    # Metric 1: sentence length variance
    # Low variance = uniform = more AI-like
    lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Normalize: std_dev of 0 is maximally AI-like, 10+ is human-like
    variance_score = 1.0 - min(std_dev / 10.0, 1.0)

    # Metric 2: type-token ratio (vocabulary diversity)
    # Low TTR = repetitive vocabulary = more AI-like
    unique_words = len(set(words))
    ttr = unique_words / total_words
    # Normalize: TTR of 1.0 is maximally human, 0.5 or below is AI-like
    ttr_score = 1.0 - min((ttr - 0.5) / 0.5, 1.0)
    ttr_score = max(0.0, ttr_score)

    # Metric 3: punctuation density
    # AI text uses punctuation predictably; very low density is AI-like
    punct_count = len(re.findall(r'[,;:\(\)\"\'\-]', text))
    punct_per_100 = (punct_count / total_words) * 100
    # Normalize: below 3 per 100 words is AI-like, above 8 is human-like
    punct_score = 1.0 - min(max(punct_per_100 - 3.0, 0.0) / 5.0, 1.0)

    stylo_score = (variance_score + ttr_score + punct_score) / 3.0
    return round(max(0.0, min(1.0, stylo_score)), 4)


# ─── Confidence Scorer ────────────────────────────────────────────────────────

def compute_confidence(llm_score, stylo_score):
    """
    Weighted average: LLM gets 65%, stylometrics get 35%.
    Returns a float between 0.0 and 1.0.
    """
    return round((llm_score * 0.65) + (stylo_score * 0.35), 4)


# ─── Label Generator ──────────────────────────────────────────────────────────

def generate_label(confidence):
    """
    Maps confidence score to one of three plain-language transparency labels.
    """
    if confidence >= 0.65:
        return (
            "Our system found strong indicators that this content was likely generated "
            "by an AI writing tool. This does not mean your work has been removed. "
            "If you wrote this yourself, you can submit an appeal and a reviewer will take a closer look."
        )
    elif confidence >= 0.36:
        return (
            "Our system was not able to confidently determine whether this content was "
            "written by a person or an AI tool. No action has been taken. If you believe "
            "this result is wrong, you can submit an appeal with context about your writing process."
        )
    else:
        return (
            "Our system found strong indicators that this content was written by a person. "
            "Thank you for sharing your work."
        )


# ─── Submission Endpoint ──────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    if not text:
        return jsonify({"error": "'text' cannot be empty"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)
    confidence = compute_confidence(llm_score, stylo_score)
    attribution = "likely_ai" if confidence >= 0.65 else ("uncertain" if confidence >= 0.36 else "likely_human")
    label = generate_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "stylo_score": stylo_score,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "stylo_score": stylo_score,
        "label": label,
        "status": "classified",
    }), 200


# ─── Audit Log Endpoint ───────────────────────────────────────────────────────

@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]}), 200


# ─── Health Check ─────────────────────────────────────────────────────────────

@app.route("/", methods=["GET"])
def index():
    return jsonify({"status": "Provenance Guard is running"}), 200


if __name__ == "__main__":
    app.run(debug=True)