import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ─── Audit Log Helpers ────────────────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_log(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ─── Signal 1: LLM via Groq ───────────────────────────────────────────────────

def llm_signal(text):
    """
    Asks Groq whether the text reads as AI-generated or human-written.
    Returns a float between 0.0 (definitely human) and 1.0 (definitely AI).
    """
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and assess the probability that it was generated by an AI writing tool.

Consider:
- Semantic coherence and predictability
- Phrasing patterns common in AI output (hedging language, overuse of transitions, overly balanced structure)
- Vocabulary choices and uniformity
- Whether the writing feels genuinely personal or templated

Respond with ONLY a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Text to analyze:
{text}"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"LLM signal error: {e}")
        return 0.5


# ─── Submission Endpoint ──────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    if not text:
        return jsonify({"error": "'text' cannot be empty"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Signal 1 only for now (Signal 2 added in M4)
    llm_score = llm_signal(text)

    # Placeholder confidence and label until M4 wires in Signal 2
    confidence = llm_score
    attribution = "likely_ai" if confidence >= 0.65 else ("uncertain" if confidence >= 0.36 else "likely_human")
    label = "[placeholder label — wired up in M5]"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "stylo_score": None,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "label": label,
        "status": "classified",
    }), 200


# ─── Audit Log Endpoint ───────────────────────────────────────────────────────

@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]}), 200


# ─── Health Check ─────────────────────────────────────────────────────────────

@app.route("/", methods=["GET"])
def index():
    return jsonify({"status": "Provenance Guard is running"}), 200


if __name__ == "__main__":
    app.run(debug=True)